### PR TITLE
WIP: tech(shrink): Shrink from smallest to biggest

### LINKED ISSUE #219: IntegralGenerator shrinker or shrinking implementation seems wrong
I think there is a bug either in the IntegralGenerator, or in the shrinking implementation. Example:
```java
@Property(maxShrinks = 100000, maxShrinkTime = 60_000_000, maxShrinkDepth = 5000)
public void testShrink(@When(seed = -4493071121312539862L) int number) {
  assertThat(number).isLessThan(8);
}
```

The starting point is `849426243` and it never shrinks lower than `424713121` (i.e. more or less divided by 2).
I think this is a bug: given enough time, shrinks and shrink depth (the difference between those 2 is hard to understand by the way), the generator should succeed to identify the smallest value that doesn't pass the property is `8` and not `424713121`.

### PR DESCRIPTION
**Pull request by Sir4ur0n**
* Align with Haskell's QuickCheck which shrinks from smallest to biggest (faster convergence)
* Migrate test string to generic platform newline feed (builds on Windows)

Closes #219.

### CODE REVIEW

**Comment by Sir4ur0n** [comment]
Please note, I wanted to add tests, but I couldn't figure out how to easily test shrinking.

if I missed something obvious please let me know and I'll add some.

My changes seem... Too easy, I'm pretty sure I missed many things. No test failing is actually weird 😨

File: core/src/main/java/com/pholser/junit/quickcheck/runner/Shrinker.java [hunk 1]
```diff
@@ -69,8 +70,7 @@ void shrink(
 
         ShrinkNode smallest =
             ShrinkNode.root(method, testClass, params, args, seeds, failure);
-        Queue<ShrinkNode> nodes = new ShrinkNodeQueue(smallest.magnitude());
-        nodes.addAll(smallest.shrinks());
+        Queue<ShrinkNode> nodes = new ArrayDeque<>(smallest.shrinks());
```
Comment (pholser) [inline core/src/main/java/com/pholser/junit/quickcheck/runner/Shrinker.java]: Can we remove class `ShrinkNodeQueue`? If so, let's do so as part of this PR.

File: core/src/test/java/com/pholser/junit/quickcheck/runner/PropertyFalsifiedUtilityClassTest.java [hunk 2]
```diff
@@ -58,10 +60,10 @@ public void counterexampleFoundWithAllParametersIsCorrect() {
             seeds,
             error);
 
-        String expected = "Property named 'mySuperProperty' failed (assertion name)\n"
-            + "With arguments: [first, second, third]\n"
-            + "Seeds for reproduction: [12345, 8842]";
-        assertEquals(expected, actual.getMessage());
+        String expected = format("Property named 'mySuperProperty' failed (assertion name)%n"
+            + "With arguments: [first, second, third]%n"
+            + "Seeds for reproduction: [12345, 8842]");
```
Comment (pholser) [inline core/src/test/java/com/pholser/junit/quickcheck/runner/PropertyFalsifiedUtilityClassTest.java]: Personal preference: use matcher `equalTo` instead of `is`.

**Comment by Sir4ur0n** [comment]
So I noticed there was a big failure while it built on my computer. I guess I got lucky as many tests rely on random :D

That being said, I played a bit with tests and noticed the shrinkers don't behave correctly for negative values :O

So I'm actually going to change more code to adapt shrinkers :/ May take a few days, sorry!

**Comment by Sir4ur0n** [comment]
By the way, I don't get this piece of code in the shrinkers, any clue? 
```java
if (negative(largestGeneric))
  results.add(negate(largestGeneric));
```
This builds a weird list of shrinks.

File: core/src/test/java/com/pholser/junit/quickcheck/runner/PropertyFalsifiedUtilityClassTest.java (hunk 2 above)
Comment (Sir4ur0n) [reply core/src/test/java/com/pholser/junit/quickcheck/runner/PropertyFalsifiedUtilityClassTest.java]: Done

File: core/src/main/java/com/pholser/junit/quickcheck/runner/Shrinker.java (hunk 1 above)
Comment (Sir4ur0n) [reply core/src/main/java/com/pholser/junit/quickcheck/runner/Shrinker.java]: Done

**Comment by Sir4ur0n** [comment]
> 
> 
> I might also add to the commit message that unlike the previous behavior, this change makes it so that as soon as a smaller counterexample is found, the previous set of untried shrinks is abandoned, in favor of shrinks of the new smaller counterexample.
> 
> Also, feel free to add yourself as a contributor in the POM.
> 
> Thanks!

Done

**Comment by Sir4ur0n** [comment]
Nevermind for the negate thing, I figured it out by checking in QuickCheck: it's done because positive numbers are considered "easier" than negative one, all things equal:
image

I will fix/adapt shrinkers.

**Comment by Sir4ur0n** [comment]
I've just pushed another version.

I added javadoc on decimal and integral generators to make it easier to understand/maintain the code in the future.

All tests passed a few times on my computer.

**Comment by pholser** [comment]
@Sir4ur0n Excellent! Thanks for your efforts -- I'll have another look soon.
